"""add published column to blog table

Revision ID: 0978cbd0a64b
Revises: 867c27e84e4e
Create Date: 2023-12-07 00:46:04.382719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0978cbd0a64b'
down_revision: Union[str, None] = '867c27e84e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'published')
    # ### end Alembic commands ###
