"""auto add vote table

Revision ID: 867c27e84e4e
Revises: fe16ce3163d3
Create Date: 2023-12-07 00:34:43.988574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867c27e84e4e'
down_revision: Union[str, None] = 'fe16ce3163d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'blog_id')
    )
    op.alter_column('blog', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blog', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blog', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_blog_content'), 'blog', ['content'], unique=True)
    op.create_index(op.f('ix_blog_id'), 'blog', ['id'], unique=True)
    op.create_index(op.f('ix_blog_title'), 'blog', ['title'], unique=True)
    op.drop_column('blog', 'published')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('blog', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_blog_title'), table_name='blog')
    op.drop_index(op.f('ix_blog_id'), table_name='blog')
    op.drop_index(op.f('ix_blog_content'), table_name='blog')
    op.alter_column('blog', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blog', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blog', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('vote')
    # ### end Alembic commands ###
